import Foundation

/// What an isolated bottle may do beyond the defaults.
public struct IsolationPolicy: Codable, Sendable, Equatable {
    /// Internet access. Off by default; anything stolen inside the bottle can't be sent out.
    public var allowNetwork: Bool
    /// Clipboard access. Off by default so programs can't read what you copy elsewhere.
    public var allowClipboard: Bool

    public init(allowNetwork: Bool = false, allowClipboard: Bool = false) {
        self.allowNetwork = allowNetwork
        self.allowClipboard = allowClipboard
    }
}

/// The file system and socket areas a sandboxed launch may touch.
public struct SandboxRules: Sendable, Equatable {
    /// Read and write denied (home folders, external disks).
    public var hiddenRoots: [URL]
    /// Read-only exceptions inside hidden roots (Wine runtime, graphics components).
    public var readOnly: [URL]
    /// Read-write exceptions inside hidden roots (prefix, caches, logs).
    public var readWrite: [URL]
    /// The only places programs may be started from.
    public var executableRoots: [URL]
    /// `/tmp/.wine-<uid>`, which holds every bottle's wineserver socket.
    public var wineServerBase: URL
    /// This bottle's own wineserver folder inside `wineServerBase`.
    public var wineServerDirectory: URL

    public init(
        hiddenRoots: [URL],
        readOnly: [URL],
        readWrite: [URL],
        executableRoots: [URL],
        wineServerBase: URL,
        wineServerDirectory: URL
    ) {
        self.hiddenRoots = hiddenRoots
        self.readOnly = readOnly
        self.readWrite = readWrite
        self.executableRoots = executableRoots
        self.wineServerBase = wineServerBase
        self.wineServerDirectory = wineServerDirectory
    }
}

/// Renders a macOS Seatbelt (SBPL) profile for `sandbox-exec`.
///
/// Starts from `allow default` so Metal, Rosetta, audio and controllers keep working, then
/// denies what malware wants: writing anywhere but the bottle, your files, starting other programs
/// (directly, through LaunchServices or as launchd jobs), other apps' sockets, the internet, Apple
/// Events, the keychain and the clipboard. In SBPL later rules override earlier ones.
public enum SandboxProfile {
    public enum RenderError: Error, Equatable {
        case missingRules(String)
        case unsupportedPath(String)
    }

    public static func render(_ rules: SandboxRules, policy: IsolationPolicy) throws -> String {
        guard !rules.hiddenRoots.isEmpty else { throw RenderError.missingRules("hiddenRoots") }
        guard !rules.executableRoots.isEmpty else { throw RenderError.missingRules("executableRoots") }

        var lines = [
            "(version 1)",
            ";; Generated by Corkscrew for an isolated bottle. Later rules override earlier ones.",
            "(allow default)",
            "",
            ";; Nothing outside the bottle is writable: no programs planted in /Applications or /opt/homebrew",
            ";; for you to run later, and the runtime stays read-only wherever it lives.",
            "(deny file-write*)",
            ";; Except devices (/dev/null, terminals), which every program writes to.",
            "(allow file-write* (subpath \"/dev\"))",
            "",
            ";; Hide personal files and other disks.",
            "(deny file-read* file-write*\(try subpaths(rules.hiddenRoots)))",
        ]
        if !rules.readOnly.isEmpty {
            lines += [";; Wine runtime and graphics components: read-only.",
                      "(allow file-read*\(try subpaths(rules.readOnly)))"]
        }
        if !rules.readWrite.isEmpty {
            lines += [";; The bottle's Windows drive, caches and logs: read-write.",
                      "(allow file-read* file-write*\(try subpaths(rules.readWrite)))"]
        }
        // Programs resolve their own paths (realpath) by looking up every parent folder, so allow
        // metadata lookups on exactly those parents. Their contents stay hidden: no listing, no reads.
        let parents = ancestors(of: rules.readOnly + rules.readWrite + rules.executableRoots)
        if !parents.isEmpty {
            lines += [";; Parent folders of the paths above: existence only, so programs can resolve their own paths.",
                      "(allow file-read-metadata\(try parents.map { "\n    (literal \(try quoted($0)))" }.joined()))"]
        }
        lines += [
            "",
            ";; Only the Wine runtime may start programs: no shells, curl, osascript or open.",
            "(deny process-exec*)",
            "(allow process-exec*\(try subpaths(rules.executableRoots)))",
            "",
            ";; wineserver opens files for its clients, so only this bottle's own server is reachable:",
            ";; not other bottles' servers (which may run unsandboxed), and no fake sockets planted for them.",
            "(allow file-write*\(try subpaths([rules.wineServerDirectory])))",
            ";; Other local sockets (ssh-agent, Docker, other apps) are off limits too.",
            "(deny network-outbound (remote unix-socket))",
            "(allow network-outbound (remote unix-socket\(try subpaths([rules.wineServerDirectory]))))",
            "",
        ]
        if policy.allowNetwork {
            lines += [";; Internet allowed for this bottle; DNS lookups go through mDNSResponder.",
                      "(allow network-outbound (remote unix-socket (subpath \"/private/var/run/mDNSResponder\")))"]
        } else {
            lines += [";; No internet, and no loopback connections to services on this Mac.",
                      "(deny network* (remote ip))",
                      "(deny network* (local ip))"]
        }
        lines += [
            "",
            ";; No starting apps or URLs through LaunchServices, and no launchd jobs: both would run outside this sandbox.",
            "(deny lsopen)",
            "(deny job-creation)",
            "",
            ";; No scripting other apps, no keychain.",
            "(deny appleevent-send)",
            "(deny mach-lookup (global-name \"com.apple.SecurityServer\") (global-name \"com.apple.securityd.xpc\"))",
        ]
        if !policy.allowClipboard {
            lines += [";; No clipboard.", "(deny mach-lookup (global-name \"com.apple.pasteboard.1\"))"]
        }
        return lines.joined(separator: "\n") + "\n"
    }

    /// Every parent folder of the given paths ("/Users", "/Users/me", …), deduplicated and sorted.
    static func ancestors(of urls: [URL]) -> [String] {
        var result = Set<String>()
        for url in urls {
            var path = (canonicalPath(url) as NSString).deletingLastPathComponent
            while path != "/" && !path.isEmpty {
                result.insert(path)
                path = (path as NSString).deletingLastPathComponent
            }
        }
        return result.sorted()
    }

    private static func subpaths(_ urls: [URL]) throws -> String {
        try urls.map { "\n    (subpath \(try quoted(canonicalPath($0))))" }.joined()
    }

    private static func quoted(_ path: String) throws -> String {
        guard !path.contains(where: { $0 == "\n" || $0 == "\r" || $0 == "\0" }) else {
            throw RenderError.unsupportedPath(path)
        }
        let escaped = path.replacingOccurrences(of: "\\", with: "\\\\").replacingOccurrences(of: "\"", with: "\\\"")
        return "\"\(escaped)\""
    }

    /// Seatbelt matches real paths, so resolve symlinks (`/tmp` → `/private/tmp`) on the longest
    /// existing ancestor and re-append the parts that don't exist yet.
    static func canonicalPath(_ url: URL) -> String {
        let fm = FileManager.default
        var existing = url.absoluteURL.standardizedFileURL.path
        var missing: [String] = []
        while existing != "/", !fm.fileExists(atPath: existing) {
            missing.insert((existing as NSString).lastPathComponent, at: 0)
            existing = (existing as NSString).deletingLastPathComponent
        }
        if let resolved = realpath(existing, nil) {
            existing = String(cString: resolved)
            free(resolved)
        }
        return missing.reduce(existing) { ($0 as NSString).appendingPathComponent($1) }
    }
}
